name: ${rootProject.projectName}
version: ${rootProject.version}
main: ${rootProject.group}.${rootProject.name}.${rootProject.projectName}
description: ${rootProject.description}
api-version: "1.21"
authors: [Mowstyl]
website: https://clanjhoo.com
softdepend: [WorldGuard, WorldEdit]
loadbefore: []
